            '2. CZ Channels': [{'name': '1. CZ Channels',
                      'thumb': 'https://i.ibb.co/mb6Q81H/CZ.jpg',
                      'video': 'https://i.ibb.co/mb6Q81H/CZ.jpg',
                      'genre': 'CZ Channels'},
                     {'name': '2. Nova',
                      'thumb': 'https://i.ibb.co/z4NMCjV/Nova.png',
                      'video': 'https://nova-live.ssl.cdn.cra.cz/channels/nova_avod/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '3. Nova 2',
                      'thumb': 'https://i.ibb.co/925Rmkq/Nova-2.png',
                      'video': 'https://nova-live.ssl.cdn.cra.cz/channels/nova_2_avod/playlist.m3u8',
                      'genre': 'CZ Channels'},
					 {'name': '4. Nova Gold',
                      'thumb': 'https://i.ibb.co/dpSZ22v/Nova-Gold.png',
                      'video': 'https://nova-live.ssl.cdn.cra.cz/channels/nova_gold_avod/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '5. Nova Action',
                      'thumb': 'https://i.ibb.co/99VYDCc/Nova-Action.jpg',
                      'video': 'https://nova-live.ssl.cdn.cra.cz/channels/nova_action_avod/playlist.m3u8',
                      'genre': 'CZ Channels'},
				     {'name': '6. Nova Cinema',
                      'thumb': 'https://i.ibb.co/rkL4pnC/Nova-Cinema.png"',
                      'video': 'https://nova-live.ssl.cdn.cra.cz/channels/nova_cinema_avod/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '7. Elektrika TV',
                      'thumb': 'https://i.ibb.co/sRVbxTv/Elektrika-TV.jpg',
                      'video': 'http://rtmp.elektrika.cz/live/myStream.sdp/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '8.Óčko',
                      'thumb': 'https://i.ibb.co/1fbv9Qq/Ocko.png',
                      'video': 'http://ocko-live.ssl.cdn.cra.cz/channels/ocko/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '9. Óčko Gold',
                      'thumb': 'https://i.ibb.co/g35N1VV/Ocko-Gold.gif',
                      'video': 'http://ocko-live.ssl.cdn.cra.cz/channels/ocko_gold/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
				     {'name': '10.  Óčko Expres',
                      'thumb': 'https://i.ibb.co/q9pwKJC/Ocko-Expres.png',
                      'video': 'http://ocko-live.ssl.cdn.cra.cz/channels/ocko_expres/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '11. Óčko STAR',
                      'thumb': 'https://i.ibb.co/HX9M2pS/Ocko-Star.png',
                      'video': 'http://ocko-live.ssl.cdn.cra.cz/channels/ocko_gold/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '12. Polar TV',
                      'thumb': 'https://i.ibb.co/8sQ8yxh/Polar.png',
                      'video': 'https://stream.polar.cz/polar/polarlive-1/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '13. HunterTV',
                      'thumb': 'https://i.ibb.co/tzNHRp9/HunterTV.png',
                      'video': 'http://www.huntertv.cz/live/4-playlist.m3u8',
                      'genre': 'CZ Channels'},
				     {'name': '14. Praha TV',
                      'thumb': 'https://i.ibb.co/yqrcmvW/PrahaTV.png',
                      'video': 'https://stream.polar.cz/prahatv/prahatvlive-1/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '15. TV Noe',
                      'thumb': 'https://i.ibb.co/z7fQ7yJ/TV-Noe.png',
                      'video': 'https://w100.quickmedia.tv/prozeta-live04/_definst_/prozeta-live04.smil/Playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '16. Retro',
                      'thumb': 'https://i.ibb.co/YPtmSrV/Retro.png',
                      'video': 'http://stream.mediawork.cz/retrotv/retrotvHQ1/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '17. Šlágr',
                      'thumb': 'https://i.ibb.co/Nx2fR74/Slagr.png',
                      'video': 'https://slagrtv-live-hls.ssl.cdn.cra.cz/channels/slagrtv/playlist/cze/live_hq.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '18. Šlágr 2',
                      'thumb': 'https://i.ibb.co/WxDvCry/Slagr2.png',
                      'video': 'http://92.62.234.233/slagr2.m3u',
                      'genre': 'CZ Channels'},
                     {'name': '19. TV Natura',
                      'thumb': 'https://i.ibb.co/K0HR49p/TV-Natura.png',
                      'video': 'http://media1.tvnatura.cz/live_out/1/live.m3u8',
                      'genre': 'CZ Channels'},
				     {'name': '20. Východočeská TV',
                      'thumb': 'https://i.ibb.co/ggWW1L0/VCTV.png',
                      'video': 'https://stream.polar.cz/vctv/vctvlive-1/playlist.m3u8',
                      'genre': 'CZ Channels'},
                     {'name': '21. TV Morava',
                      'thumb': 'https://i.ibb.co/LRfyxNG/TV-Morava.png',
                      'video': 'https://i.ibb.co/LRfyxNG/TV-Morava.png',
                      'genre': 'CZ Channels'}
                     ],