            '3. Movies': [{'name': '1. Movies',
                      'thumb': 'https://i.ibb.co/zbt3KHp/Movies.png',
                      'video': 'https://i.ibb.co/zbt3KHp/Movies.png',
                      'genre': 'Movies'},
                     {'name': '2. Spongebob ve Filmu: Houba Na Útěku [CZ Dabing] [2020]',
                      'thumb': 'https://i.ibb.co/LrZ2Rcn/Spongebob-Sponge-On-The-Run.jpg',
                      'video': 'https://files.fm/down.php?i=nhumjsc9j',
                      'genre': 'Movies'},
                     {'name': '3. Spongebob ve Filmu: Houba Na Suchu [CZ Dabing] [2015]',
                      'thumb': 'https://i.ibb.co/bzwL5b7/Spongebob-Sponge-Out-Of-Water.jpg',
                      'video': 'https://files.fm/down.php?i=etgfyb5uy',
                      'genre': 'Movies'},
                      {'name': '4. Spongebob ve Filmu  [CZ Dabing] [2004]',
                      'thumb': 'https://i.ibb.co/Sn2HkJc/Spongebob-Ve-Filmu-2004.jpg',
                      'video': 'https://files.fm/down.php?i=k8mpkg7kd',
                      'genre': 'Movies'},
                     {'name': '5. The Windermere Children [EN + CZ Tit] [2020]',
                      'thumb': 'https://i.ibb.co/zN1MPXj/The-Windermere-Children.jpg',
                      'video': 'https://files.fm/down.php?i=r6fpnuwrz',
                      'genre': 'Movies'}
                     ]}
