VIDEOS = {'1. SK Channels': [{'name': '1. SK Channels',
                       'thumb': 'https://i.ibb.co/2cH2kVB/SK.jpg',
                       'video': 'https://i.ibb.co/2cH2kVB/SK.jpg',
                       'genre': 'SK Channels'},
                      {'name': '2. JoJ',
                       'thumb': 'https://i.ibb.co/SccZK6g/JOJ.png',
                       'video': 'http://nn2.joj.sk/hls/joj-720.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '3. JoJ Plus',
                       'thumb': 'https://i.ibb.co/G5VWSNM/Plus.png',
                       'video': 'http://nn2.joj.sk/hls/jojplus-540.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '4. JoJ Family',
                       'thumb': 'https://i.ibb.co/MNRvsnZ/JOJ-Family.jpg',
                       'video': 'http://nn.geo.joj.sk/hls/family-360.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '5. Wau',
                       'thumb': 'https://i.ibb.co/kmDHqy3/WAU.png',
                       'video': 'https://nn.geo.joj.sk/live/wau-index.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '6. TA3',
                       'thumb': 'https://i.ibb.co/vcSFT8C/TA3.png',
                       'video': 'https://tv.parrottv.tk/TA3.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '7. Fashion TV',
                       'thumb': 'https://i.ibb.co/XzBpYkL/Fashion-TV.png',
                       'video': 'http://lb.streaming.sk/fashiontv/stream/playlist.m3u8?fluxustv.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '8. Rik',
                       'thumb': 'https://i.ibb.co/WPy9w4n/Rik.png',
                       'video': 'https://nn.geo.joj.sk/live/hls/rik-540.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '9. TV Lux',
                       'thumb': 'https://i.ibb.co/4jx6gzZ/TV-Lux.png',
                       'video': 'http://live.tvlux.sk:1935/lux/lux.stream_360p/chunklist_w1295439472.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '10. Life TV HD',
                       'thumb': 'https://i.ibb.co/3YktrSX/Life-TV.png',
                       'video': 'https://lifetv.mpks.sk/s.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '11. Senzi TV',
                       'thumb': 'https://i.ibb.co/fnMky9c/Senzi.png',
                       'video': 'http://109.74.144.130/live/senzitest/playlist.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '12. Televizia OSEM',
                       'thumb': 'https://i.ibb.co/wRG1nkt/TV-OSEM.png',
                       'video': 'http://109.74.145.11:1935/tv8/ngrp:tv8.stream_all/playlist.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '13. TV Raj',
                       'thumb': 'https://i.ibb.co/J3TT3bZ/TV-Raj.png',
                       'video': 'http://ottst05.flexitv.sk/2827-tv-pc.m3u8',
                       'genre': 'SK Channels'},
                      {'name': '14. Bardejovská TV',
                       'thumb': 'https://i.ibb.co/CVrPbfy/BTV.jpg',
                       'video': 'rtmp://s1.media-planet.sk:80/live/bardejov1?checkedby:hlscat.com',
                       'genre': 'SK Channels'},
                      {'name': '15. KoŠice:Dnes',
                       'thumb': 'https://i.ibb.co/phBd44T/Kosice-Dnes.jpg',
                       'video': 'http://lb.streaming.sk/tvnasa/stream/playlist.m3u8?checkedby:hlscat.com',
                       'genre': 'SK Channels'},
                      {'name': '16. TV Nové Zámky',
                       'thumb': 'https://i.ibb.co/Y2XDLmH/NZTV.png',
                       'video': 'http://s1.media-planet.sk:80/live/novezamky/BratuMarian.m3u8?checkedby:hlscat.com',
                       'genre': 'SK Channels'},
                      {'name': '17. TV Reduta',
                       'thumb': 'https://i.ibb.co/S6snjM0/TVR.png',
                       'video': 'rtmp://s1.media-planet.sk:80/live/reduta?checkedby:hlscat.com',
                       'genre': 'SK Channels'},
                      {'name': '18. TV Ružinov',
                       'thumb': 'https://i.ibb.co/mzbMHpg/TVRU.png',
                       'video': 'http://lb.streaming.sk/tvruzinov/stream/playlist.m3u8?checkedby:hlscat.com',
                       'genre': 'SK Channels'},
                      {'name': '19. TV Turzovka',
                       'thumb': 'https://i.ibb.co/bmTMnr4/TVT.png',
                       'video': 'rtmp://s1.media-planet.sk:80/live/turzovka?checkedby:hlscat.com',
                       'genre': 'SK Channels'}
                      ],